### ISSUE TITLE
7. Algorithm

### ISSUE THREAD

**Issue by bo23519** [johnsfarrell/djmixes#10]
As a user, I want to be able to see/parse the original songs from certain DJ mixes, so I can find songs that I am interested in

**Comment by johnsfarrell** [comment]
Initial working implementation with Shazamio and Demucs

**Comment by johnsfarrell** [comment]
Working on implementing design that is more readable and maintainable before uploading to repo

**Comment by johnsfarrell** [comment]
Finished
